### ISSUE TITLE
Menu crashes when user passes invalid input

### ISSUE THREAD

**Issue by rfilipczak** [IIS-ZPI/ZPI2023_zaoczni_BogoSort#49]
```
Banking app
Menu

1. Currency’s statistics
2. Aggregated sessions
3. Changes distribution
4. Exit

Enter your choice: a
Traceback (most recent call last):
  File "C:\Edu\Sem7\zarzadzanie\ZPI2023_zaoczni_BogoSort\src\components\run.py", line 11, in <module>
    main()
  File "C:\Edu\Sem7\zarzadzanie\ZPI2023_zaoczni_BogoSort\src\components\run.py", line 7, in main
    app.run()
  File "C:\Edu\Sem7\zarzadzanie\ZPI2023_zaoczni_BogoSort\src\components\useriohandler.py", line 18, in run
    self.choice, self.days, self.currencies, self.file_path = self.menu.run()
                                                              ^^^^^^^^^^^^^^^
  File "C:\Edu\Sem7\zarzadzanie\ZPI2023_zaoczni_BogoSort\src\components\menu.py", line 188, in run
    return self.__menu_loop()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Edu\Sem7\zarzadzanie\ZPI2023_zaoczni_BogoSort\src\components\menu.py", line 171, in __menu_loop
    choice = int(input("Enter your choice: "))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'a'
Press any key to continue . . . 
```

steps to reproduce:
1. $ .\_run.bat
2. type 'a'

**Comment by Mati-IR** [comment]
Issue successfully fixed by rfilipczak
